### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by keithbriggs** [rmcgibbo/reftagger#10]
http://reftag.rmcgibbo.org doesn't work.

**Comment by rmcgibbo** [comment]
I'll remove that from the readme.

**Comment by keithbriggs** [comment]
Thanks - but that leaves the package without any documentation, as far as I can see.   How do I figure out how to use it?

**Comment by rmcgibbo** [comment]
This was a weekend project from 3 years ago.

**Comment by keithbriggs** [comment]
ok
